name: apitest
description: >-
  RICOH THETA WebAPI test implementation with Dart/Flutter.
dependencies:
  http: ^0.12.2
  args: ^1.6.0
  theta:
    # git:
    #   url: https://github.com/codetricity/theta
    #   ref: main
    # change the path below to the path above for production use
    path: ../theta
  dcli: ^0.41.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0

repository: https://github.com/theta360developers/webapi