name: apitest
description: >-
  RICOH THETA WebAPI test implementation with Dart/Flutter.
dependencies:
  http: ^0.12.2
  args: ^1.6.0
  theta:
    path: packages/theta

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0

repository: https://github.com/theta360developers/webapi